name: acme_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https//github.com:Ephenodrom/Dart-Acme-Client
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  basic_utils: ^3.6.0
  json_annotation: any
  dio: ^4.0.0
  jose: ^0.3.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: any
  json_serializable: any
