name: acme_client
description: ACME client written in Dart
version: 1.0.1
homepage: https://github.com/Ephenodrom/Dart-Acme-Client
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  basic_utils: ^3.6.0
  json_annotation: ^4.1.0
  dio: ^4.0.0
  jose: ^0.3.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
