name: acme_client
description: ACME client which allows you to obtain a HTTPS Certificate from any ACME CA such as Lets Encrypt.
version: 2.0.0
homepage: https://github.com/Ephenodrom/Dart-Acme-Client
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  basic_utils: ^5.5.4
  json_annotation: ^4.1.0
  dio: ^5.0.0
  jose: ^0.3.5
dev_dependencies: 
  lints: ^6.1.0
  test: ^1.16.0
  build_runner: ^2.3.0
  json_serializable: ^6.6.1
  document_throws: ^0.2.1
