services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:latest
    command: -config /test/pebble-config.json -dnsserver challtestsrv:8053
    environment:
      PEBBLE_VA_NOSLEEP: "1"
      PEBBLE_WFE_NONCEREJECT: "0"
      PEBBLE_AUTHZREUSE: "0"
    ports:
      - "14000:14000"
      - "15000:15000"
    volumes:
      - ./pebble-config.json:/test/pebble-config.json:ro
    depends_on:
      - challtestsrv

  challtestsrv:
    image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "8053:8053"
      - "8055:8055"
      - "8443:8443"
